#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODE="${1:-}"

if [[ -z "$MODE" ]]; then
  printf 'Usage: scripts/write-app-local-envs.sh <lan-http|caddy-https> [public-host]\n' >&2
  exit 1
fi

write_env() {
  local file_path="$1"
  local public_host="$2"
  local allowed_origins="$3"
  local api_url="$4"
  local cpg_url="$5"
  local store_url="$6"
  local wallet_url="$7"
  local chough_url="${8:-}"

  {
    printf '# Generated by scripts/write-app-local-envs.sh (%s)\n' "$MODE"
    printf 'NEXT_PUBLIC_API_URL=%s\n' "$api_url"
    printf 'NEXT_PUBLIC_CPG_PORTAL_URL=%s\n' "$cpg_url"
    printf 'NEXT_PUBLIC_STORE_DASHBOARD_URL=%s\n' "$store_url"
    printf 'NEXT_PUBLIC_WALLET_URL=%s\n' "$wallet_url"
    printf '\n'
    printf 'PUBLIC_HOST=%s\n' "$public_host"
    printf 'ALLOWED_DEV_ORIGINS=%s\n' "$allowed_origins"
    if [[ -n "$chough_url" ]]; then
      printf 'CHOUGH_URL=%s\n' "$chough_url"
    fi
  } > "$file_path"
}

url_host() {
  local value="$1"
  value="${value#*://}"
  value="${value%%/*}"
  value="${value%%:*}"
  printf '%s\n' "$value"
}

case "$MODE" in
  lan-http)
    PUBLIC_HOST_VALUE="${2:-${PUBLIC_HOST:-}}"
    if [[ -z "$PUBLIC_HOST_VALUE" ]]; then
      printf 'Missing LAN host. Pass it as arg2 or set PUBLIC_HOST.\n' >&2
      exit 1
    fi

    API_URL="http://${PUBLIC_HOST_VALUE}:3000"
    BACKOFFICE_URL="http://${PUBLIC_HOST_VALUE}:3001"
    CPG_URL="http://${PUBLIC_HOST_VALUE}:3002"
    STORE_URL="http://${PUBLIC_HOST_VALUE}:3003"
    WALLET_URL="http://${PUBLIC_HOST_VALUE}:3004"
    CHOUGH_URL_VALUE="${CHOUGH_URL:-http://127.0.0.1:8080}"
    ALLOWED_ORIGINS_VALUE="${ALLOWED_DEV_ORIGINS:-$PUBLIC_HOST_VALUE}"
    ;;
  caddy-https)
    API_URL="${QOA_API_URL:-https://api.qoa.test}"
    BACKOFFICE_URL="${QOA_BACKOFFICE_URL:-https://admin.qoa.test}"
    CPG_URL="${QOA_CPG_URL:-https://cpg.qoa.test}"
    STORE_URL="${QOA_STORE_URL:-https://store.qoa.test}"
    WALLET_URL="${QOA_WALLET_URL:-https://wallet.qoa.test}"
    CHOUGH_URL_VALUE="${QOA_CHOUGH_URL:-https://voice.qoa.test}"
    ALLOWED_ORIGINS_VALUE="${ALLOWED_DEV_ORIGINS:-admin.qoa.test,api.qoa.test,cpg.qoa.test,store.qoa.test,wallet.qoa.test,voice.qoa.test}"
    ;;
  *)
    printf 'Unknown mode: %s\n' "$MODE" >&2
    exit 1
    ;;
esac

write_env "$ROOT_DIR/apps/backoffice/.env.local" "$(url_host "$BACKOFFICE_URL")" "$ALLOWED_ORIGINS_VALUE" "$API_URL" "$CPG_URL" "$STORE_URL" "$WALLET_URL"
write_env "$ROOT_DIR/apps/cpg-portal/.env.local" "$(url_host "$CPG_URL")" "$ALLOWED_ORIGINS_VALUE" "$API_URL" "$CPG_URL" "$STORE_URL" "$WALLET_URL"
write_env "$ROOT_DIR/apps/store-dashboard/.env.local" "$(url_host "$STORE_URL")" "$ALLOWED_ORIGINS_VALUE" "$API_URL" "$CPG_URL" "$STORE_URL" "$WALLET_URL" "$CHOUGH_URL_VALUE"
write_env "$ROOT_DIR/apps/digital-wallet/.env.local" "$(url_host "$WALLET_URL")" "$ALLOWED_ORIGINS_VALUE" "$API_URL" "$CPG_URL" "$STORE_URL" "$WALLET_URL"

rm -rf \
  "$ROOT_DIR/apps/backoffice/.next" \
  "$ROOT_DIR/apps/cpg-portal/.next" \
  "$ROOT_DIR/apps/store-dashboard/.next" \
  "$ROOT_DIR/apps/digital-wallet/.next"

printf 'Wrote app .env.local files for %s\n' "$MODE"
