FROM node:20-alpine

RUN apk add --no-cache curl unzip

RUN curl -fsSL https://bun.sh/install | sh
ENV PATH="/root/.bun/bin:$PATH"

WORKDIR /app

COPY package.json ./
COPY bun.lock ./

RUN bun install --frozen-lockfile

COPY . .

RUN bun run db:migrate

EXPOSE 3000

CMD ["bun", "index.js"]
